/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-ImageCaptureCore.h
 #	source generated by 4D Plugin Wizard
 #	Project : ImageCaptureCore
 #	author : miyako
 #	2020/03/04
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_IMAGECAPTURECORE_H
#define PLUGIN_IMAGECAPTURECORE_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "C_BLOB.h"
#include "ARRAY_TEXT.h"

#include "4DPlugin-JSON.h"

#define CALLBACK_IN_NEW_PROCESS 0
#define CALLBACK_SLEEP_TIME 59

#include "json.h"

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

typedef enum
{
    param_data_type_text = 0,
    param_data_type_blob = 1
}param_data_type_t;

typedef enum
{
    param_scan_type_file = 0,
    param_scan_type_data = 1,
    param_scan_type_success = 2,
    param_scan_type_error = 3
}param_scan_type_t;

typedef CUTF16String param_scan_context_info_t;
typedef CUTF16String param_scan_info_t;
typedef CUTF16String param_scan_path_t;
typedef std::vector<uint8_t> param_scan_data_t;

#import <objc/runtime.h>
#import <ImageCaptureCore/ImageCaptureCore.h>
#define ICDeviceAnyScanner ICDeviceTypeMaskScanner\
| ICDeviceLocationTypeMaskLocal\
| ICDeviceLocationTypeMaskShared\
| ICDeviceLocationTypeMaskBonjour\
| ICDeviceLocationTypeMaskBluetooth\
| ICDeviceLocationTypeMaskRemote

@interface Scanner : NSObject<ICScannerDeviceDelegate>
{
    ICScannerDevice *_scanner;
    BOOL _waiting;
    NSInteger _error;
}

- (id)initWithScanner:(ICScannerDevice *)scanner;
- (void)setScanner:(ICScannerDevice *)scanner;
- (BOOL)openForSource:(ICScannerFunctionalUnitType)source timeout:(NSUInteger)seconds;
- (BOOL)closeWithTimeout:(NSUInteger)seconds;
- (void)requestScan;
- (void)cancelScan;

@end

@interface ScannerBrowser : NSObject
<ICDeviceBrowserDelegate>
{
    NSMutableArray *_scanners;
}

- (ICScannerDevice *)scannerForIdentifier:(NSString *)uuid;

@property(retain, readonly) NSMutableArray *scanners;

@end

#pragma mark -

void ICA_SCANNERS_LIST(PA_PluginParameters params);
void ICA_SET_SCAN_OPTION(PA_PluginParameters params);
void ICA_OPEN_SCANNER_SESSION(PA_PluginParameters params);
void ICA_CLOSE_SCANNER_SESSION(PA_PluginParameters params);
void ICA_SCAN(PA_PluginParameters params);
void ICA_CANCEL(PA_PluginParameters params);
void ICA_Get_scan_option(PA_PluginParameters params);

#endif /* PLUGIN_IMAGECAPTURECORE_H */
